//src/themes/definitions.ts
import type { Theme, ThemeId } from "./types";

export const THEMES: Record<ThemeId, Theme> = {
  elegante: {
    id: "elegante",
    name: "Elegante",
    description: "Clásico y sereno: crema, dorado y fotos en arco.",
    colors: {
      background: "#faf6ef",
      surface: "#ffffff",
      text: "#2b2622",
      muted: "#7a6f64",
      primary: "#7a5c2e",
      accent: "#b08d57",
      border: "#e3d9c6",
    },
    fonts: { heading: "cormorant", body: "lora" },
    heading: "centered",
    dish: "centered",
    divider: "ornament",
    price: "plain",
    tag: "outline",
    image: { aspect: "1/1", shape: "arch" },
    spacing: "airy",
    texture: "paper",
    radius: "md",
  },

  moderno: {
    id: "moderno",
    name: "Moderno",
    description: "Limpio y ligero: tarjetas, números y precios en píldora.",
    colors: {
      background: "#f6f7f9",
      surface: "#ffffff",
      text: "#111827",
      muted: "#6b7280",
      primary: "#0f766e",
      accent: "#f59e0b",
      border: "#e5e7eb",
    },
    fonts: { heading: "poppins", body: "inter" },
    heading: "numbered",
    dish: "card",
    divider: "none",
    price: "pill",
    tag: "pill",
    image: { aspect: "4/3", shape: "rounded" },
    spacing: "normal",
    texture: "none",
    radius: "lg",
  },

  rustico: {
    id: "rustico",
    name: "Rústico",
    description: "Cálido y artesanal: papel kraft, banners y puntos guía.",
    colors: {
      background: "#f1e6d3",
      surface: "#f8f0e1",
      text: "#3b2a1e",
      muted: "#7b6450",
      primary: "#8c3b1a",
      accent: "#5f7a3a",
      border: "#d4bf9f",
    },
    fonts: { heading: "amatic", body: "lora" },
    heading: "banner",
    dish: "leader",
    divider: "dots",
    price: "plain",
    tag: "square",
    image: { aspect: "1/1", shape: "rounded" },
    spacing: "normal",
    texture: "linen",
    radius: "sm",
  },

  premium: {
    id: "premium",
    name: "Premium oscuro",
    description: "Lujoso y nocturno: fondo negro, dorado y fotos con texto encima.",
    colors: {
      background: "#0f0e0c",
      surface: "#1a1815",
      text: "#f3ece0",
      muted: "#a39a8b",
      primary: "#d4af37",
      accent: "#b8913a",
      border: "#2e2a24",
    },
    fonts: { heading: "playfair", body: "montserrat" },
    heading: "left-line",
    dish: "overlay",
    divider: "line",
    price: "outline",
    tag: "outline",
    image: { aspect: "4/3", shape: "rounded" },
    spacing: "airy",
    texture: "grain",
    radius: "md",
  },

  editorial: {
    id: "editorial",
    name: "Editorial / Revista",
    description: "Atrevido y tipográfico: titulares enormes y fotos que alternan lados.",
    colors: {
      background: "#f4f1ea",
      surface: "#ffffff",
      text: "#141414",
      muted: "#5c5c5c",
      primary: "#c1121f",
      accent: "#141414",
      border: "#cfcabd",
    },
    fonts: { heading: "abril", body: "worksans" },
    heading: "editorial",
    dish: "magazine",
    divider: "double",
    price: "accent",
    tag: "text",
    image: { aspect: "3/2", shape: "square" },
    spacing: "normal",
    texture: "none",
    radius: "none",
  },
};

export const THEME_LIST: Theme[] = Object.values(THEMES);

export function getTheme(id: string): Theme {
  return (THEMES as Record<string, Theme>)[id] ?? THEMES.elegante;
}